# What this script will do:
# 1. Download the repo 
#   checkout: https://github.com/actions/checkout 
# 2. Download and install .NET
#   setup-dotnet: https://github.com/actions/setup-dotnet
# 3. Build the code
#   https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
# 4. Publish to Azure
#   function-action: https://github.com/Azure/functions-action

#BEWARE
#Any function that is already published in the Function App will be replaced

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Get the publish profile value following this tutorial here:
#   https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
# 2. Set up the publish profile value as a secret in your repository with the name:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 3. In the "env" settings, change the "your-app-name" to the name of your Azure Function App
# 4. If you are using a different envirement on Github, set in the "environment" value inside "jobs"

name: Deploy DotNet project to Azure Function App

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: your-app-name  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
  environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
